// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkpqfabhsdanybxaaqsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrcHFmYWJoc2RhbnlieGFhcXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTU4OTYsImV4cCI6MjA3MzE5MTg5Nn0.NndxiUvJa8kOL5jvVXwy0c1BTdnL_ELsO9tpHRSF8xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});